apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-creator-binding
subjects:
- kind: User
  name: "arn:aws:sts::851725417042:assumed-role/eksClusterRole/AWSCLI-Session"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: crd-creator-role
  apiGroup: rbac.authorization.k8s.io

